name: ai_chat_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 状態管理ライブラリ
  flutter_riverpod: ^2.1.3
  # OpenAI GPT-3 との連携を容易にするSDK
  chat_gpt_sdk: ^2.0.7 
  # 音声認識ライブラリ
  speech_to_text: ^6.1.1
  # 環境変数管理ライブラリ
  flutter_dotenv: ^5.0.2 
  # テキストやファイルの共有機能
  share_plus: ^6.3.2 
  # URLを開くためのライブラリ
  url_launcher: ^6.1.10 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # コード品質向上のためのLintルール
  flutter_lints:

flutter:


  uses-material-design: true


